### ISSUE TITLE
Thai channel

### ISSUE THREAD

**Issue by Snoman168** [akkradet/IPTV-THAI#6]
The channels are no longer working.Error code 404
Thanks

**Comment by akkradet** [comment]
updated

**Comment by akkradet** [comment]
Updated

**Comment by Snoman168** [comment]
Thank youSent from my Galaxy
-------- Original message --------From: akkradet ***@***.***> Date: 11/8/24  01:11  (GMT+08:00) To: akkradet/IPTV-THAI ***@***.***> Cc: Snoman168 ***@***.***>, Author ***@***.***> Subject: Re: [akkradet/IPTV-THAI] Thai channel (Issue #6) 
Updated
