### ISSUE TITLE
See blank screen on latest m3u file from time to time

### ISSUE THREAD

**Issue by chinkung** [akkradet/IPTV-THAI#8]
When I try to use the latest FREETV.m3u, the app keeps loading and eventually displays a blank screen for channels random from time to time.

Tested using Tivimate, wiseplay
Tested on NT internet, True Internet

Could you please check ?

**Comment by chinkung** [comment]
I observe that it occasionally loads and sometimes does not, which may be attributed to internet connectivity issues.

I will close this issue

**Comment by akkradet** [comment]
Checked Normal

**Comment by chinkung** [comment]
I never face this intermittent issue with playlists created prior to August 11, 2024, may be provider issue.
